/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2024-08-04 10:33:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mgmt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Management Groups Configuration</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            /* Remove height: 100vh; to allow scrolling */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background-color: #f0f8ff; /* Light navy blue background */\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #e6e6fa; /* Light navy blue background */\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            /* Add minimum height to ensure content fits without scrolling */\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #000080; /* Navy blue */\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #000080; /* Navy blue */\r\n");
      out.write("        }\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        th {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #000080; /* Navy blue */\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"text\"], input[type=\"number\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"], input[type=\"button\"] {\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background-color: #000080; /* Navy blue */\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"]:hover, input[type=\"button\"]:hover {\r\n");
      out.write("            background-color: #0000cd; /* Medium blue */\r\n");
      out.write("        }\r\n");
      out.write("        .button-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <form action=\"resourceGroups.jsp\" method=\"post\">\r\n");
      out.write("            <h1>Management Groups Configuration</h1>\r\n");
      out.write("            \r\n");
      out.write("            ");

                int numManagementGroups = Integer.parseInt(request.getParameter("numManagementGroups"));
                int numSubscriptions = Integer.parseInt(request.getParameter("numSubscriptions"));
                String clientId = request.getParameter("clientId");
                String clientSecret = request.getParameter("clientSecret");
                String tenantId = request.getParameter("tenantId");
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <input type=\"hidden\" name=\"numManagementGroups\" value=\"");
      out.print( numManagementGroups );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"numSubscriptions\" value=\"");
      out.print( numSubscriptions );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"clientId\" value=\"");
      out.print( clientId );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"clientSecret\" value=\"");
      out.print( clientSecret );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"tenantId\" value=\"");
      out.print( tenantId );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <table>\r\n");
      out.write("                ");

                    for (int i = 0; i < numManagementGroups; i++) {
                
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\"><h2>Management Group ");
      out.print( i + 1 );
      out.write("</h2></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th><label for=\"mgName");
      out.print( i );
      out.write("\">Management Group Name ");
      out.print( i + 1 );
      out.write(":</label></th>\r\n");
      out.write("                        <td><input type=\"text\" id=\"mgName");
      out.print( i );
      out.write("\" name=\"mgName");
      out.print( i );
      out.write("\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th><label for=\"mgDisplayName");
      out.print( i );
      out.write("\">Display Name ");
      out.print( i + 1 );
      out.write(":</label></th>\r\n");
      out.write("                        <td><input type=\"text\" id=\"mgDisplayName");
      out.print( i );
      out.write("\" name=\"mgDisplayName");
      out.print( i );
      out.write("\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th><label for=\"mgSubscriptionIds");
      out.print( i );
      out.write("\">Subscription IDs (comma-separated) ");
      out.print( i + 1 );
      out.write(":</label></th>\r\n");
      out.write("                        <td><input type=\"text\" id=\"mgSubscriptionIds");
      out.print( i );
      out.write("\" name=\"mgSubscriptionIds");
      out.print( i );
      out.write("\" ></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");

                    for (int i = 0; i < numSubscriptions; i++) {
                
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\"><h2>Subscription ");
      out.print( i + 1 );
      out.write("</h2></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th><label for=\"subscriptionId");
      out.print( i );
      out.write("\">Subscription ID ");
      out.print( i + 1 );
      out.write(":</label></th>\r\n");
      out.write("                        <td><input type=\"text\" id=\"subscriptionId");
      out.print( i );
      out.write("\" name=\"subscriptionId");
      out.print( i );
      out.write("\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th><label for=\"numResourceGroups");
      out.print( i );
      out.write("\">Number of Resource Groups for Subscription ");
      out.print( i + 1 );
      out.write(":</label></th>\r\n");
      out.write("                        <td><input type=\"number\" id=\"numResourceGroups");
      out.print( i );
      out.write("\" name=\"numResourceGroups");
      out.print( i );
      out.write("\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <div class=\"button-container\">\r\n");
      out.write("                            <input type=\"button\" value=\"Back\" onclick=\"window.history.back()\">\r\n");
      out.write("                            <input type=\"submit\" value=\"Next\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
