name: Move and Deploy Terraform Configuration

on:
  push:
    paths:
      - 'main.tf'  # Trigger this workflow when main.tf is created or updated

jobs:
  move-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move main.tf to terraform folder
        run: |
          mkdir -p terraform
          mv main.tf terraform/main.tf

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Create login script
        run: |
          echo '#!/bin/bash' > login.sh
          echo 'echo "AZURE_CLIENT_ID: $AZURE_CLIENT_ID"' >> login.sh
          echo 'echo "AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET"' >> login.sh
          echo 'echo "AZURE_TENANT_ID: $AZURE_TENANT_ID"' >> login.sh
          echo 'az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"' >> login.sh
          chmod +x login.sh

      - name: Log in to Azure CLI
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: ./login.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0  # Specify the version of Terraform to use

      - name: Set Terraform Variables and Initialize
        env:
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform Configuration
        env:
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve
        working-directory: terraform
